spring:
  application.name: storage
  jmx.enabled: false
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017
#      database: storage
  jackson:
    default-property-inclusion: non_empty
    deserialization:
      fail-on-unknown-properties: false
  kafka:
    bootstrap-servers: localhost:9093

server.port: 10001

eureka:
  instance:
    hostname: search
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EURIKAIP}:8761/eureka/

management.endpoints.web.exposure.include: '*'


