AWSTemplateFormatVersion: 2010-09-09
Resources:
    InstanceSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
          GroupDescription: Allow all protocols to client host
          VpcId: vpc-0753c57f
          SecurityGroupIngress:
          - IpProtocol: -1
            FromPort: -1
            ToPort: -1
            CidrIp: 46.229.218.0/24
          - IpProtocol: -1
            FromPort: -1
            ToPort: -1
            CidrIp: 5.188.107.104/29
          - IpProtocol: -1
            FromPort: -1
            ToPort: -1
            CidrIp: 185.44.13.32/29
          SecurityGroupEgress:
          - IpProtocol: -1
            FromPort: -1
            ToPort: -1
            CidrIp: 0.0.0.0/0
Outputs:
    SecurityGroupID:
        Description: The id of security group
        Value: {"Fn::GetAtt": ["InstanceSecurityGroup","GroupId"]}

