AWSTemplateFormatVersion: 2010-09-09
Resources:
    InstanceSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
          GroupDescription: Allow all protocols to client host
          VpcId: vpc-0753c57f
          SecurityGroupIngress:
          - IpProtocol: -1
            FromPort: -1
            ToPort: -1
            CidrIp: 0.0.0.0/0
          SecurityGroupEgress:
          - IpProtocol: -1
            FromPort: -1
            ToPort: -1
            CidrIp: 0.0.0.0/0
Outputs:
    SecurityGroupID:
        Description: The id of security group
        Value: {"Fn::GetAtt": ["InstanceSecurityGroup","GroupId"]}

